home:
    path:     /
    defaults: { _controller: CoolerMainBundle:Home:index }

findabar:
    path:     /findabar
    defaults: { _controller: CoolerMainBundle:Home:findaBar }
search_beer:
    path:     /searchBeer
    defaults: { _controller: CoolerMainBundle:Ajax:searchBeer }


test:
    path:     /test
    defaults: { _controller: CoolerMainBundle:Home:test }
beer:
    path:     /beer/{beerId}
    defaults: { _controller: CoolerMainBundle:Beer:index }
